import React from "react";

//LIBRERIAS Y FUNCIONES IMPORTANTES
import { type Metadata } from "next";
import { ClerkProvider} from "@clerk/nextjs";
import { esMX } from "@clerk/localizations";


//COMPONETES Y DISEÑO
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

//METADATA
export const metadata: Metadata = {
  title: "Zcatalogo",
  description: "Generated by create next app",
};



//FUNCION PRINCIPAL LAYOUT PRINCIPAL
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>){
  

  return (
    <ClerkProvider localization={esMX}>
      <html lang="es">
        <body>
            <Header/>
            
          <main className="flex">
            <Sidebar />
            <div className="flex-grow">{children}</div>
          </main>

          <Footer/>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
