import React from "react";

//LIBRERIAS Y FUNCIONES IMPORTANTES
import { type Metadata } from "next";
import { ClerkProvider} from "@clerk/nextjs";
import { esMX } from "@clerk/localizations";


//COMPONETES Y DISEÑO
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

//SHADCN
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/Sidebar shadcn/app-sidebar"
import { ThemeProvider } from "@/lib/theme-provider";
import { ModeToggle } from "@/components/mode-toogle";

//METADATA
export const metadata: Metadata = {
  title: "Zcatalogo",
  description: "Generated by create next app",
};



//FUNCION PRINCIPAL LAYOUT PRINCIPAL
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>){
  

  return (
    <ClerkProvider localization={esMX}>
      <html lang="es" suppressHydrationWarning>

        <body className="flex flex-wrap border-red-700 border-2">
           <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>

          
         <SidebarProvider>
      <AppSidebar />
      <main className="w-full">
        <Navbar />
        <SidebarTrigger />
        <ModeToggle />
        {children}

      </main>
    </SidebarProvider>

          <Footer/>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
